Container:
    ProductsScreen:
        id: products_screen
        name: 'ProductsScreen'
        manager: 'container'
    LoginScreen:
        id: login_screen
        name: 'LoginScreen'
        manager: 'container'

<ProductsScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        spacing: ('10dp')
        padding: '20dp'
        FitImage:
            source: 'View/images/logo.png'
            width: '250dp'
            size_hint: None, None
            pos_hint: {'center_x': 0.5, 'top': 1}
        MDTextField:
            hint_text: "Логин"
            mode: "round"
            md_bg_color: (223/255, 182/255, 120/255, 1)
            size_hint_x: .75
            pos_hint: {'center_x': .5}
        MDTextField:
            hint_text: "Пароль"
            mode: "round"
            md_bg_color: 223/255, 182/255, 120/255, 1
            size_hint_x: .75
            pos_hint: {'center_x': .5}
        MDTextButton:
            text: "Забыли пароль?"
            custom_color: 0, 1, 0, 1
        MDFillRoundFlatButton:
            text: 'Вход'
            pos_hint: {"center_x": 0.5}
            size_hint_x: .75
        MDFillRoundFlatButton:
            pos_hint: {"center_x": 0.5}
            size_hint_x: .75
            text: 'Продолжить без аккаунта'
