#:import Window kivy.core.window.Window
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
Container:
    id: container
    LoginScreen:
        id: login_screen
        name: 'LoginScreen'
        manager: 'container'
    RegisterScreen:
        id: register_screen
        name: 'RegisterScreen'
        manager: 'container'
    ProductsScreen:
        id: products_screen
        name: 'ProductsScreen'
        manager: 'container'



<ItemBackdropFrontLayer@TwoLineAvatarListItem>
    icon: "android"

    IconLeftWidget:
        icon: root.icon


<MyBackdropFrontLayer@ScrollView>
    pos_hint: {"top": 1, 'center_x': 0.5}
    size_hint: 1, 1
    do_scroll_x: False
    MDBoxLayout:
        padding: 20, 20
        orientation: 'vertical'
        size_hint: 1, 0.3
        GridLayout:
            pos_hint: {'center_y': 0.5, 'center_x': 0.5}
            cols: 2
            rows: 2
            Image:
                pos_hint: {'center_y': 0.5, 'center_x': 0.5}
                source: 'App/View/images/ubka.jpg'
                size_hint: 0.5, 0.5
            MDLabel:
                pos_hint: {'center_y': 0.5, 'center_x': 0.5}
                size_hint: 0.5, 0.5
                text: 'Юбка ПМ-201'
            MDLabel:
                pos_hint: {'center_y': 0.5, 'center_x': 0.5}
                size_hint: 0.5, 0.5
                text: 'Количество: 1'
            MDTextButton:
                pos_hint: {'center_y': 0.5, 'center_x': 0.5}
                size_hint: 0.5, 0.5
                text: 'Купить'
                on_press:
                    pass

                
    


<MyBackdropBackLayer@MDBoxLayout>
    size_hint: None, None
    pos_hint: {"center_x": .5, "top": 1}
    md_bg_color: (223/255, 182/255, 120/255, 1)
    MDTextButton:
        text: 'Аккаунт'
        on_press:
            app.root.current = 'LoginScreen'

<ProductsScreen>:
    MDBackdrop:
        id: backdrop
        left_action_items: [['menu', lambda x: self.open()]]
        title: 'Etalina'
        header_text: 'Каталог'
        back_layer_color: (223/255, 182/255, 120/255, 1)

        MDBackdropBackLayer:
            MyBackdropBackLayer:
                id: backlayer

        MDBackdropFrontLayer:
            MyBackdropFrontLayer:
                backdrop: backdrop
    # MDBoxLayout:
    #     pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    #     adaptive_size: True
    #     orientation: 'vertical'
    #     spacing: '20dp'
    #     padding: '20dp'
<RegisterScreen>:
    MDBoxLayout:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        adaptive_size: True
        orientation: 'vertical'
        spacing: '20dp'
        padding: '20dp'
        LogoImage:
            pos_hint: {'center_x': 0.5, 'top': 1}
        MDLabel:
            id: response
            text: ''
            pos_hint: {'center_x': .5}
            padding_y: 50
        MDTextField:
            hint_text: 'Логин'
            id: login_field
            mode: 'round'
            size_hint_x: .60
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextField:
            hint_text: 'Пароль'
            id: password_field
            password: True
            mode: 'round'
            md_bg_color: 223/255, 182/255, 120/255, 1
            size_hint_x: .60
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDFillRoundFlatButton:
            text: 'Регистрация'
            on_press:
                root.reg_account()
            bold: True
            pos_hint: {'center_x': 0.5}
            md_bg_color: (223/255, 182/255, 120/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
        MDFillRoundFlatButton:
            text: 'Есть аккаунт'
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'LoginScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
        MDFillRoundFlatButton:
            padding_y: 25
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'ProductsScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
            text: 'Продолжить без аккаунта'

<LogoImage@Image>:
    source: 'App/View/images/logo.png'
    size_hint: 1.4, None

<LoginScreen>:
    MDBoxLayout:
        #pos_hint: {'x': 0, 'y': 0}
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        adaptive_size: True
        orientation: 'vertical'
        spacing: '20dp'
        padding: '20dp'
        LogoImage:
            pos_hint: {'center_x': 0.5, 'top': 1}
        MDLabel:
            id: response
            text: ''
            pos_hint: {'center_x': .5}
            padding_y: 50
        MDTextField:
            hint_text: 'Логин'
            id: login_field
            mode: 'round'
            size_hint_x: .60
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextField:
            hint_text: 'Пароль'
            id: password_field
            password: True
            mode: 'round'
            md_bg_color: 223/255, 182/255, 120/255, 1
            size_hint_x: .60
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextButton:
            text: 'Забыли пароль?'
            color: (0/255, 102/255, 255/255, 1)
            size_hint_x: .75
            pos_hint: {'center_x': .5}
        MDFillRoundFlatButton:
            text: 'Вход'
            on_press:
                root.post_auth()
            bold: True
            pos_hint: {'center_x': 0.5}
            md_bg_color: (223/255, 182/255, 120/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
        MDFillRoundFlatButton:
            text: 'Регистрация'
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'RegisterScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
        MDFillRoundFlatButton:
            padding_y: 25
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'ProductsScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
            text: 'Продолжить без аккаунта'