#:import Window kivy.core.window.Window
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
Container:
    size_hint: 1, 1
    id: container
    LoginScreen:
        id: login_screen
        name: 'LoginScreen'
        manager: 'container'
    ProductsScreen:
        id: products_screen
        name: 'ProductsScreen'
        manager: 'container'
    RegisterScreen:
        id: register_screen
        name: 'RegisterScreen'
        manager: 'container'

<ItemBackdropFrontLayer@TwoLineAvatarListItem>:
    icon: "android"
    IconLeftWidget:
        icon: root.icon


<MyBackdropFrontLayer@ScrollView>:
    pos_hint: {"top": 1, 'center_x': 0.5}
    size_hint: 1, 1
    do_scroll_x: False
    MDBoxLayout:
        id: this_box
        padding: 20, 20
        orientation: 'vertical'
        size_hint: 1, 1
        height: sum(x.height for x in self.children)

<MyBackdropBackLayer@MDBoxLayout>:
    size_hint: 1, None
    md_bg_color: (223/255, 182/255, 120/255, 1)
    orientation: 'vertical'
    pos_hint: {'top': 1}
    spacing: '20dp'
    MDTextButton:
        size_hint_x: 1
        pos_hint: {'center_x': 0.5, 'top': 1}
        text: 'Аккаунт'
        halign: 'center'
        on_press:
            app.root.current = 'LoginScreen'
    MDTextButton:
        size_hint_x: 1
        pos_hint: {'center_x': 0.5, 'top': 1}
        text: 'Выйти из аккаунта'
        halign: 'center'
        on_press:
            app.root.exit_from_account()
            app.root.current = 'LoginScreen'
    MDTextButton:
        size_hint_x: 1
        pos_hint: {'center_x': 0.5, 'top': 1}
        text: 'Выйти из приложения'
        halign: 'center'
        on_press:
            app.stop()

<ProductsScreen>:
    MDBackdrop:
        id: backdrop
        left_action_items: [['menu', lambda x: self.open()]]
        title: 'Etalina'
        header_text: 'Каталог'
        back_layer_color: (223/255, 182/255, 120/255, 1)

        MDBackdropBackLayer:
            MyBackdropBackLayer:

        MDBackdropFrontLayer:
            MyBackdropFrontLayer:
                id: this_front
                backdrop: backdrop

<RegisterScreen>:
    MDBoxLayout:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        adaptive_size: True
        orientation: 'vertical'
        spacing: '20dp'
        padding: '20dp'
        LogoImage:
            pos_hint: {'center_x': 0.5, 'top': 1}
        MDLabel:
            id: response
            text: ''
            pos_hint: {'center_x': .5}
            padding_y: 50
        MDTextFieldRound:
            hint_text: 'Логин'
            id: login_field
            size_hint_x: .60
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextFieldRound:
            hint_text: 'Пароль'
            id: password_field
            password: True
            md_bg_color: 223/255, 182/255, 120/255, 1
            size_hint_x: .60
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDFillRoundFlatButton:
            text: 'Регистрация'
            on_press:
                root.reg_account()
            bold: True
            pos_hint: {'center_x': 0.5}
            md_bg_color: (223/255, 182/255, 120/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
        MDFillRoundFlatButton:
            text: 'Есть аккаунт'
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'LoginScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
        MDFillRoundFlatButton:
            padding_y: 25
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'ProductsScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
            text: 'Продолжить без аккаунта'

<LogoImage@Image>:
    source: 'App/View/images/logo.png'
    size_hint: 1.4, None

<LoginScreen>:
    MDBoxLayout:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        adaptive_size: True
        orientation: 'vertical'
        spacing: '30dp'
        LogoImage:
            pos_hint: {'center_x': 0.5, 'top': 1}
        MDLabel:
            id: response
            text: ''
            pos_hint: {'center_x': .5}
            padding_y: 50
        MDTextFieldRound:
            hint_text: 'Логин'
            id: login_field
            size_hint_x: 1
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextFieldRound:
            hint_text: 'Пароль'
            id: password_field
            password: True
            md_bg_color: 223/255, 182/255, 120/255, 1
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextButton:
            text: 'Забыли пароль?'
            color: (0/255, 102/255, 255/255, 1)
            pos_hint: {'center_x': .5}
            halign: 'left'
            size_hint_x: 1
        MDFillRoundFlatButton:
            text: 'Вход'
            on_press:
                root.post_auth()
            bold: True
            pos_hint: {'center_x': 0.5}
            md_bg_color: (223/255, 182/255, 120/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: 1
        MDFillRoundFlatButton:
            text: 'Регистрация'
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'RegisterScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: 1
        MDFillRoundFlatButton:
            padding_y: 25
            on_press:
                app.root.transition.duration = .18
                app.root.transition.direction = 'left'
                app.root.current = 'ProductsScreen'
            pos_hint: {'center_x': 0.5}
            md_bg_color: (237/255, 237/255, 237/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: 1
            text: 'Продолжить без аккаунта'