<ProductsScreen>:
    MDBoxLayout:
        pos_hint: {'x': 0, 'y': 0}
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        adaptive_size: True
        orientation: 'vertical'
        spacing: ('10dp')
        padding: '20dp'
        FitImage:
            source: 'App/View/images/logo.png'
            width: '250dp'
            size_hint: None, None
            pos_hint: {'center_x': 0.5, 'top': 0}
        MDTextField:
            hint_text: "Логин"
            mode: "round"
            size_hint_x: .75
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextField:
            hint_text: "Пароль"
            password: True
            mode: "round"
            md_bg_color: 223/255, 182/255, 120/255, 1
            size_hint_x: .75
            pos_hint: {'center_x': .5}
            line_color_normal: 0, 0, 0, 1 # Обводка
            line_color_focus: 0, 0, 0, 1 # Обводка
            hint_text_color_focus: 0, 0, 0, 1
            fill_color_normal: 1, 1, 1, 1 # Задний фон
            text_color_normal: 0, 0, 0, 1 # Текст
            text_color_focus: 0, 0, 0, 1 # Текст
        MDTextButton:
            text: "Забыли пароль?"
            custom_color: 0, 1, 0, 1
        MDFillRoundFlatButton:
            text: 'Вход'
            pos_hint: {"center_x": 0.5}
            md_bg_color: (223/255, 182/255, 120/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
        MDFillRoundFlatButton:
            pos_hint: {"center_x": 0.5}
            md_bg_color: (223/255, 182/255, 120/255, 1)
            text_color: 0, 0, 0, 1
            size_hint_x: .75
            text: 'Продолжить без аккаунта'